apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "rudder.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.spec }}
  {{ $k | snakecase | upper }}: {{$v | quote}}
  {{- end }}
