apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "rudder.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret }}
  {{ $k | snakecase | upper }}: {{$v | quote}}
  {{- end }}
