apiVersion: v1
kind: Service
metadata:
  name: {{ include "rudder.fullname" . }}
  labels:
    {{- include "rudder.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "rudder.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: application
