{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rudder.serviceAccountName" . }}
  labels:
    {{- include "rudder.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
  {{- with .Values.serviceAccount.annotations }}
annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
